//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGZipLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YGZipLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The AES encryption stream is broken. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_AES_STREAM_BROKEN {
            get {
                return ResourceManager.GetString("ERRMSG_AES_STREAM_BROKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_ALREDY_FINISHED {
            get {
                return ResourceManager.GetString("ERRMSG_ALREDY_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The ZIP file cannot be read. (The central directory not found.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_BAD_ZIPFILE {
            get {
                return ResourceManager.GetString("ERRMSG_BAD_ZIPFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parent directory traversal is not allowed in zip entry names.: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_DIR_TRAVERSAL_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERRMSG_DIR_TRAVERSAL_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The directory cannot be output.: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_DIRECTORY_CANNOT_OUTPUT {
            get {
                return ResourceManager.GetString("ERRMSG_DIRECTORY_CANNOT_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password is incorrect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_INCORRECT_PASSWORD {
            get {
                return ResourceManager.GetString("ERRMSG_INCORRECT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal error. AES mask array generation status invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_INTERNAL_AESMASKGEN_ERROR {
            get {
                return ResourceManager.GetString("ERRMSG_INTERNAL_AESMASKGEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal error. There is an unprocessed output queue. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_INTERNAL_QUEUE_ERROR {
            get {
                return ResourceManager.GetString("ERRMSG_INTERNAL_QUEUE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid AES mode specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_INVALID_AESMODE {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_AESMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The directory name contains invalid characters.: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_INVALID_DIRNAME {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_DIRNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name contains invalid characters.: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_INVALID_FILENAME {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other threads have been aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_OTHER_THREAD_ABORTED {
            get {
                return ResourceManager.GetString("ERRMSG_OTHER_THREAD_ABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parent directory traversal is not allowed in zip entry names.: centralDirectory={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_OUTPUT_DIR_TRAVERSAL_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERRMSG_OUTPUT_DIR_TRAVERSAL_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output directory does not exist.: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_OUTPUT_DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_OUTPUT_DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output file name contains invalid characters.: centralDirectory={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_OUTPUT_FILENAME_INVALID {
            get {
                return ResourceManager.GetString("ERRMSG_OUTPUT_FILENAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password length exceeds 65536 bytes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("ERRMSG_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absolute or drive-rooted paths are not allowed in zip entry names.: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_ROOT_PATH {
            get {
                return ResourceManager.GetString("ERRMSG_ROOT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file addition task is running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_TASK_RUNNING {
            get {
                return ResourceManager.GetString("ERRMSG_TASK_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The temporary directory does not exist.: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_TEMPDIR_NOTFOUND {
            get {
                return ResourceManager.GetString("ERRMSG_TEMPDIR_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This compression method is not supported.: centralDirectory={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_UNKNOWN_COMPRESSION_METHOD {
            get {
                return ResourceManager.GetString("ERRMSG_UNKNOWN_COMPRESSION_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception was thrown during zip decompression.: centralDirectory={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_UNZIP_ERROR {
            get {
                return ResourceManager.GetString("ERRMSG_UNZIP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The ZIP file stream is broken.(CRC Error): centralDirectory={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_ZIP_STREAM_BROKEN_CRC {
            get {
                return ResourceManager.GetString("ERRMSG_ZIP_STREAM_BROKEN_CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The ZIP file stream is broken.(Size): centralDirectory={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERRMSG_ZIP_STREAM_BROKEN_SIZE {
            get {
                return ResourceManager.GetString("ERRMSG_ZIP_STREAM_BROKEN_SIZE", resourceCulture);
            }
        }
    }
}
